#!/bin/bash
cd ${0%/*} || exit 1

wclean processPoroPerm
wclean processPoroSurf
wclean processConcentration
wclean processMaxVelocity
wclean processMeshCellCenters
wclean processSolidArea
wclean processFF

