#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake processPoroPerm
wmake processPoroSurf
wmake processMaxVelocity
wmake processMeshCellCenters
wmake processSolidArea
wmake processFF
wmake processPerm
# ----------------------------------------------------------------- end-of-file
