#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake simpleDBSFoam
wmake simpleGCFoam
wmake simpleNanoFoam
# ----------------------------------------------------------------- end-of-file
